config {
  type: "view",
  schema: "Gold",
  name: "vw_top_movies",
  description: "Top 10 filmes ordenados pela nota média (mínimo de 100 avaliações)"
}

WITH metricas_filmes AS (
  SELECT 
    movie_id,
    COUNT(user_id) AS total_avaliacoes,
    AVG(nota_avaliacao) AS rating_medio
  FROM ${ref("slv_fact_ratings")}
  GROUP BY movie_id
)

SELECT
  f.titulo,
  f.generos,
  f.ano_lancamento,
  ROUND(m.rating_medio, 2) AS rating_medio,
  m.total_avaliacoes
FROM metricas_filmes m
INNER JOIN ${ref("slv_movies")} f
  ON m.movie_id = f.movie_id
WHERE m.total_avaliacoes >= 100
ORDER BY rating_medio DESC, total_avaliacoes DESC
LIMIT 10