config {
  type: "operations",
  hasOutput: true,
  schema: "MovieLens_Beliefs",
  name: "brz_user_recommendation_history"
}

CREATE OR REPLACE EXTERNAL TABLE ${self()} (
  userID STRING,
  tstamp STRING,
  movieID STRING,
  predictedRating STRING
)
OPTIONS (
  format = 'CSV',
  uris = ['gs://bronze-dpt/user_recommendation_history.csv'],
  skip_leading_rows = 1,
  ignore_unknown_values = true,
  quote = '"'
);